//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Na_datu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Документ.
    /// </summary>
    // *** Start programmer edit section *** (Документ CustomAttributes)

    // *** End programmer edit section *** (Документ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокументE", new string[] {
            "Дата as \'Дата\'",
            "Тип as \'Тип\'",
            "Фамилия as \'Фамилия\'",
            "Ответственный as \'Ответственный\'",
            "Ответственный.ФамилияИ as \'Фамилия И\'",
            "Ответственный.Должность"}, Hidden=new string[] {
            "Ответственный.ФамилияИ"})]
    [MasterViewDefineAttribute("ДокументE", "Ответственный", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФамилияИ")]
    [View("ДокументL", new string[] {
            "Дата as \'Дата\'",
            "Тип as \'Тип\'",
            "Фамилия as \'Фамилия\'",
            "Ответственный.ФамилияИ as \'Фамилия И\'"})]
    public class Документ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private string fТип;
        
        private string fФамилия;
        
        private IIS.Na_datu.Ответственный fОтветственный;
        
        // *** Start programmer edit section *** (Документ CustomMembers)

        // *** End programmer edit section *** (Документ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Дата CustomAttributes)

        // *** End programmer edit section *** (Документ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Дата Get start)

                // *** End programmer edit section *** (Документ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Документ.Дата Get end)

                // *** End programmer edit section *** (Документ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Дата Set start)

                // *** End programmer edit section *** (Документ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Документ.Дата Set end)

                // *** End programmer edit section *** (Документ.Дата Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Тип CustomAttributes)

        // *** End programmer edit section *** (Документ.Тип CustomAttributes)
        [StrLen(255)]
        public virtual string Тип
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Тип Get start)

                // *** End programmer edit section *** (Документ.Тип Get start)
                string result = this.fТип;
                // *** Start programmer edit section *** (Документ.Тип Get end)

                // *** End programmer edit section *** (Документ.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Тип Set start)

                // *** End programmer edit section *** (Документ.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Документ.Тип Set end)

                // *** End programmer edit section *** (Документ.Тип Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Документ.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Фамилия Get start)

                // *** End programmer edit section *** (Документ.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Документ.Фамилия Get end)

                // *** End programmer edit section *** (Документ.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Фамилия Set start)

                // *** End programmer edit section *** (Документ.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Документ.Фамилия Set end)

                // *** End programmer edit section *** (Документ.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Документ.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Документ.Ответственный CustomAttributes)
        [PropertyStorage(new string[] {
                "Ответственный"})]
        [NotNull()]
        public virtual IIS.Na_datu.Ответственный Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Ответственный Get start)

                // *** End programmer edit section *** (Документ.Ответственный Get start)
                IIS.Na_datu.Ответственный result = this.fОтветственный;
                // *** Start programmer edit section *** (Документ.Ответственный Get end)

                // *** End programmer edit section *** (Документ.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Ответственный Set start)

                // *** End programmer edit section *** (Документ.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Документ.Ответственный Set end)

                // *** End programmer edit section *** (Документ.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокументE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументE", typeof(IIS.Na_datu.Документ));
                }
            }
            
            /// <summary>
            /// "ДокументL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументL", typeof(IIS.Na_datu.Документ));
                }
            }
        }
    }
}
