//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Na_datu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ответственный.
    /// </summary>
    // *** Start programmer edit section *** (Ответственный CustomAttributes)

    // *** End programmer edit section *** (Ответственный CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтветственныйE", new string[] {
            "ФамилияИ as \'Фамилия И\'",
            "Должность as \'Должность\'"})]
    [AssociatedDetailViewAttribute("ОтветственныйE", "Стаж", "СтажE", true, "", "Стаж", true, new string[] {
            ""})]
    [View("ОтветственныйL", new string[] {
            "ФамилияИ as \'Фамилия И\'",
            "Должность as \'Должность\'"})]
    public class Ответственный : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилияИ;
        
        private string fДолжность;
        
        private IIS.Na_datu.DetailArrayOfСтаж fСтаж;
        
        // *** Start programmer edit section *** (Ответственный CustomMembers)

        // *** End programmer edit section *** (Ответственный CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Ответственный.Должность CustomAttributes)

        // *** End programmer edit section *** (Ответственный.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (Ответственный.Должность Get start)

                // *** End programmer edit section *** (Ответственный.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (Ответственный.Должность Get end)

                // *** End programmer edit section *** (Ответственный.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ответственный.Должность Set start)

                // *** End programmer edit section *** (Ответственный.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Ответственный.Должность Set end)

                // *** End programmer edit section *** (Ответственный.Должность Set end)
            }
        }
        
        /// <summary>
        /// ФамилияИ.
        /// </summary>
        // *** Start programmer edit section *** (Ответственный.ФамилияИ CustomAttributes)

        // *** End programmer edit section *** (Ответственный.ФамилияИ CustomAttributes)
        [StrLen(255)]
        public virtual string ФамилияИ
        {
            get
            {
                // *** Start programmer edit section *** (Ответственный.ФамилияИ Get start)

                // *** End programmer edit section *** (Ответственный.ФамилияИ Get start)
                string result = this.fФамилияИ;
                // *** Start programmer edit section *** (Ответственный.ФамилияИ Get end)

                // *** End programmer edit section *** (Ответственный.ФамилияИ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ответственный.ФамилияИ Set start)

                // *** End programmer edit section *** (Ответственный.ФамилияИ Set start)
                this.fФамилияИ = value;
                // *** Start programmer edit section *** (Ответственный.ФамилияИ Set end)

                // *** End programmer edit section *** (Ответственный.ФамилияИ Set end)
            }
        }
        
        /// <summary>
        /// Ответственный.
        /// </summary>
        // *** Start programmer edit section *** (Ответственный.Стаж CustomAttributes)

        // *** End programmer edit section *** (Ответственный.Стаж CustomAttributes)
        public virtual IIS.Na_datu.DetailArrayOfСтаж Стаж
        {
            get
            {
                // *** Start programmer edit section *** (Ответственный.Стаж Get start)

                // *** End programmer edit section *** (Ответственный.Стаж Get start)
                if ((this.fСтаж == null))
                {
                    this.fСтаж = new IIS.Na_datu.DetailArrayOfСтаж(this);
                }
                IIS.Na_datu.DetailArrayOfСтаж result = this.fСтаж;
                // *** Start programmer edit section *** (Ответственный.Стаж Get end)

                // *** End programmer edit section *** (Ответственный.Стаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ответственный.Стаж Set start)

                // *** End programmer edit section *** (Ответственный.Стаж Set start)
                this.fСтаж = value;
                // *** Start programmer edit section *** (Ответственный.Стаж Set end)

                // *** End programmer edit section *** (Ответственный.Стаж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтветственныйE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтветственныйE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтветственныйE", typeof(IIS.Na_datu.Ответственный));
                }
            }
            
            /// <summary>
            /// "ОтветственныйL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтветственныйL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтветственныйL", typeof(IIS.Na_datu.Ответственный));
                }
            }
        }
    }
}
