//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Na_datu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стаж.
    /// </summary>
    // *** Start programmer edit section *** (Стаж CustomAttributes)

    // *** End programmer edit section *** (Стаж CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтажE", new string[] {
            "Стаж as \'Стаж\'"})]
    public class Стаж : ICSSoft.STORMNET.DataObject
    {
        
        private int fСтаж;
        
        private IIS.Na_datu.Ответственный fОтветственный;
        
        // *** Start programmer edit section *** (Стаж CustomMembers)

        // *** End programmer edit section *** (Стаж CustomMembers)

        
        /// <summary>
        /// Стаж.
        /// </summary>
        // *** Start programmer edit section *** (Стаж.Стаж CustomAttributes)

        // *** End programmer edit section *** (Стаж.Стаж CustomAttributes)
        public virtual int Стаж
        {
            get
            {
                // *** Start programmer edit section *** (Стаж.Стаж Get start)

                // *** End programmer edit section *** (Стаж.Стаж Get start)
                int result = this.fСтаж;
                // *** Start programmer edit section *** (Стаж.Стаж Get end)

                // *** End programmer edit section *** (Стаж.Стаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стаж.Стаж Set start)

                // *** End programmer edit section *** (Стаж.Стаж Set start)
                this.fСтаж = value;
                // *** Start programmer edit section *** (Стаж.Стаж Set end)

                // *** End programmer edit section *** (Стаж.Стаж Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Na_datu.Ответственный.
        /// </summary>
        // *** Start programmer edit section *** (Стаж.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Стаж.Ответственный CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Ответственный"})]
        public virtual IIS.Na_datu.Ответственный Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Стаж.Ответственный Get start)

                // *** End programmer edit section *** (Стаж.Ответственный Get start)
                IIS.Na_datu.Ответственный result = this.fОтветственный;
                // *** Start programmer edit section *** (Стаж.Ответственный Get end)

                // *** End programmer edit section *** (Стаж.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стаж.Ответственный Set start)

                // *** End programmer edit section *** (Стаж.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Стаж.Ответственный Set end)

                // *** End programmer edit section *** (Стаж.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтажE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтажE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтажE", typeof(IIS.Na_datu.Стаж));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Стаж.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтаж CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтаж CustomAttributes)
    public class DetailArrayOfСтаж : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Na_datu.DetailArrayOfСтаж members)

        // *** End programmer edit section *** (IIS.Na_datu.DetailArrayOfСтаж members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Стаж by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Стаж.
        /// </summary>
        public DetailArrayOfСтаж(IIS.Na_datu.Ответственный fОтветственный) : 
                base(typeof(Стаж), ((ICSSoft.STORMNET.DataObject)(fОтветственный)))
        {
        }
        
        public IIS.Na_datu.Стаж this[int index]
        {
            get
            {
                return ((IIS.Na_datu.Стаж)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Na_datu.Стаж dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
